[build]
  publish = "dist"     # Netlify will deploy files from /dist
  command = ""         # No build step needed (static site)

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html (for SPAs or deep linking)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

