github.com:
    users:
        divinetruthascension-dev:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: divinetruthascension-dev
